// Copyright (c) 2026 GraphX by roipeker.

// Retained scene, rendering, interaction, and Flutter-hosting core for GraphX.

import 'dart:async';
import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:http/http.dart' as http;

part 'core/config.dart';
part 'core/environment.dart';
part 'core/runtime.dart';
part 'core/semantics.dart';
part 'core/signal.dart';
part 'core/geometry/geom.dart';
part 'core/geometry/numeric_buffer.dart';
part 'core/geometry/path_geometry.dart';
part 'core/input/cursor.dart';
part 'core/input/focus.dart';
part 'core/input/hit_area.dart';
part 'core/input/hit_inspection.dart';
part 'core/input/hit_test.dart';
part 'core/input/input.dart';
part 'core/input/input_host.dart';
part 'core/input/node_pointer.dart';
part 'core/resources/assets.dart';
part 'core/resources/texture.dart';
part 'core/resources/texture_atlas.dart';
part 'core/scene/callback_root.dart';
part 'core/scene/node.dart';
part 'core/scene/node_bounds.dart';
part 'core/scene/node_geometry.dart';
part 'core/scene/node_space.dart';
part 'core/scene/node_transform.dart';
part 'core/scene/root.dart';
part 'core/scene/stage.dart';
part 'core/scene/stage_support.dart';
part 'core/scene/viewport_group.dart';
part 'debug/inspection.dart';
part 'debug/inspection_activity.dart';
part 'debug/inspection_capture.dart';
part 'debug/inspection_diagnostics.dart';
part 'debug/inspection_picker.dart';
part 'debug/inspection_rendering.dart';
part 'debug/inspection_resource_references.dart';
part 'debug/inspection_resources.dart';
part 'debug/stats.dart';
part 'debug/timing.dart';
part 'debug/trace.dart';
part 'flutter/focus_host.dart';
part 'flutter/geometry_extensions.dart';
part 'flutter/graphx_view.dart';
part 'flutter/semantics_host.dart';
part 'flutter/portal/portal.dart';
part 'flutter/portal/portal_domain.dart';
part 'flutter/portal/portal_host.dart';
part 'flutter/runtime_provider.dart';
part 'flutter/stage_snapshot.dart';
part 'flutter/widget_controller.dart';
part 'gesture/gesture.dart';
part 'gesture/tap.dart';
part 'gesture/drag.dart';
part 'gesture/long_press.dart';
part 'gesture/node_drag.dart';
part 'graphics/shader.dart';
part 'graphics/shader_bindings.dart';
part 'graphics/shader_assets.dart';
part 'graphics/graphics_style.dart';
part 'graphics/graphics_batch.dart';
part 'graphics/graphics.dart';
part 'graphics/graphics_bounds.dart';
part 'graphics/graphics_hit_area.dart';
part 'graphics/shape.dart';
part 'render/cache.dart';
part 'render/color_transform.dart';
part 'render/composite.dart';
part 'render/clip_hit.dart';
part 'render/filter.dart';
part 'render/filter_public.dart';
part 'render/node_snapshot.dart';
part 'render/pixel_scale.dart';
part 'render/render_context.dart';
part 'render/render_context_color.dart';
part 'render/render_session.dart';
part 'render/render_view.dart';
part 'render/subtree_painter.dart';
part 'visuals/animated_image.dart';
part 'visuals/canvas_node.dart';
part 'visuals/defaults.dart';
part 'visuals/icon.dart';
part 'visuals/image.dart';
part 'visuals/image_batch.dart';
part 'visuals/image_batch_public.dart';
part 'visuals/shader_node.dart';
part 'visuals/text.dart';
